# Generated by Django 3.1.8 on 2022-11-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Configuration', '0001_initial'),
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(verbose_name='Enrollment Date')),
                ('is_paid_subscription', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=20, verbose_name='Paid')),
                ('course_id', models.ManyToManyField(to='Courses.Course')),
                ('student_id', models.ManyToManyField(to='Configuration.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Learning_progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.TimeField(verbose_name='Begin Time')),
                ('completion_time', models.TimeField(verbose_name='Completion Time')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('Finshed', 'Finshed')], max_length=20, verbose_name='Status')),
                ('course_chapter_content_id', models.ManyToManyField(to='Courses.Course_chapter_content')),
                ('enrollment_id', models.ManyToManyField(to='Master.Enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_score', models.IntegerField(null=True, verbose_name='Rating')),
                ('feedback_text', models.CharField(max_length=250, verbose_name='Feedback')),
                ('submission_date', models.DateField(verbose_name='Submission-date')),
                ('enrollment_id', models.ManyToManyField(to='Master.Enrollment')),
            ],
        ),
    ]
