# Generated by Django 3.1.8 on 2022-11-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(max_length=100, verbose_name='Chapter title')),
                ('num_of_reading', models.IntegerField(null=True, verbose_name='Reading books')),
                ('num_of_video', models.IntegerField(null=True, verbose_name='No of Video')),
                ('num_of_assignment', models.IntegerField(null=True, verbose_name='No of Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Content_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=20, verbose_name='Content Type')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=50, verbose_name='Language Name')),
            ],
        ),
        migrations.CreateModel(
            name='Course_chapter_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=20, verbose_name='Is Mandatory')),
                ('time_required_in_sec', models.IntegerField(null=True, verbose_name='Time required in sec')),
                ('is_open_for_free', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=20, verbose_name='Is Free')),
                ('content_type_id', models.ManyToManyField(to='Courses.Content_Type')),
                ('course_chapter_id', models.ManyToManyField(to='Courses.Chapters')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=200, verbose_name='Course title')),
                ('course_brief', models.CharField(max_length=4000, verbose_name='Course brief')),
                ('num_of_chapters', models.IntegerField(null=True, verbose_name='No of Chapters')),
                ('course_fee', models.IntegerField(null=True, verbose_name='Course Fee')),
                ('instructor_id', models.ManyToManyField(to='Configuration.Instructor')),
                ('language_id', models.ManyToManyField(to='Courses.Language')),
            ],
        ),
        migrations.AddField(
            model_name='chapters',
            name='course_id',
            field=models.ManyToManyField(to='Courses.Course'),
        ),
    ]
