# Generated by Django 3.1.8 on 2022-11-10 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent_phone_no',
            new_name='phone',
        ),
    ]
