# Generated by Django 3.1.8 on 2022-11-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0002_auto_20221110_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
